;
; File generated by cc65 v 2.10.5
;
	.fopt		compiler,"cc65 v 2.10.5"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.import		_tgi_setviewpage
	.import		_tgi_setdrawpage
	.export		_drawPending
	.export		_interruptOccurred
	.export		_drawpage
	.export		_vbl

.segment	"DATA"

_drawPending:
	.byte	$00
_interruptOccurred:
	.byte	$00
_drawpage:
	.byte	$00

; ---------------------------------------------------------------
; void __near__ vbl (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_vbl: near

.segment	"CODE"

	pha
	phx
	phy

	inc		_interruptOccurred
	lda     _drawPending
	beq     @L1
	lda     _drawpage
	jsr     _tgi_setviewpage
	lda     _drawpage
	eor	#$01
	sta     _drawpage
	jsr     _tgi_setdrawpage
	stz     _drawPending
@L1:


    ply
	plx
	pla
	rts

.endproc

